name: Hello World
on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: actions/checkout@v3
      - uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
      - name: CI-Build
        run: |
          echo 'Running in MSYS2!'
          mkdir -p /c/dumps
          ./procdump64.exe -accepteula -ma -i /c/dumps
