name: Hello World
on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: actions/checkout@v3
      - uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: false

      - name: Setup JIT debugging
        run: |
          mkdir -p /c/dumps
          ./procdump64.exe -accepteula -ma -i /c/dumps

      - name: Run 64bit
        env:
          MSYS: winjitdebug
        continue-on-error: true
        run: |
          ./crash-64.exe

      - name: Show dumps
        run: |
          ls -l /c/dumps

      - name: Run 32bit
        env:
          MSYS: winjitdebug
        continue-on-error: true
        run: |
          ./crash-32.exe

      - name: Show dumps
        run: |
          ls -l /c/dumps
