name: Hello World
on: [push, pull_request]

jobs:
  build:
    env:
      MSYS: winjitdebug

    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: actions/checkout@v3
      - uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: false
          install: git base-devel mingw-w64-x86_64-gcc mingw-w64-x86_64-meson

      - name: Setup JIT debugging
        run: |
          mkdir -p /c/dumps
          ./procdump64.exe -accepteula -ma -i /c/dumps
          ./procdump.exe -accepteula -ma -i /c/dumps

      - name: Test
        continue-on-error: true
        run: |
          git clone --depth 1 https://github.com/msys2/MINGW-packages
          cd MINGW-packages/mingw-w64-gobject-introspection
          makepkg-mingw -Csf --noarchive --noconfirm --nocheck

      - name: Show dumps
        run: |
          shopt -s nullglob
          for f in /c/dumps/*; do
            echo "::group::[$f]"
            ./minidump-stackwalk.exe "$f"
            echo "::endgroup::"
          done
